Course_planner_task:
    description: >
      Based on the topic {topic}, the learner's objectives {objective}, and prerequisites {prerequisites}, create a well-structured course outline. The structure should be divided into sections and subsections, and must facilitate progressive learning.
    expected_output: >
      A hierarchical course structure formatted in JSON or markdown, including section titles and their associated subsections. {topic}, its prerequisites: {prerequisites}, and its objectives: {objective}.
    agent: Course_planner

content_writer_task:
    description: >
      For each section and subsection defined in the course plan, write educational content that is clear, structured, and adapted to the learner's level.
    expected_output: >
      A detailed and well-written content block for each subsection, formatted in markdown, using headings, lists, and examples when relevant. the subsection, ready to be displayed.
    agent: Content_writer
    context:
      - Course_planner_task

Quiz_builder_task: 
    description: >
      Create a quiz composed of at least 10 multiple-choice questions (MCQs) for each session. The questions should evaluate the learner's understanding of all subsections within the session.
    expected_output: >
      A set of MCQs (question + 4 options + correct answer) formatted in JSON or markdown for each session.
    agent: quiz_builder
    context: 
      - content_writer_task

project_builder_task:
  description: >
    Design a hands-on project at the end of each section. The project should apply the concepts learned, reinforce understanding, and promote creativity. It should include clear instructions, expected deliverables, and evaluation criteria.
  expected_output: >
    A project description document for each section, including objectives, steps, resources (if needed), and deliverables.
  agent: project_builder
  context:
    - Course_planner_task
    - content_writer_task

Course_compiler_task:
  description: >
    Assemble a complete course package on {topic}, using the structure, content,
    videos, quizzes, and project materials generated by the other agents. "
    Format everything clearly and coherently, organizing the course into sections and subsections.Ensure consistency in titles, language, and instructional flow. Return a clean, well-structured document
    (preferably in Markdown or HTML format) ready to be served via API or exported."
  expected_output: >
    A fully compiled course document including: 
    - Course title and introduction
    - Sections and subsections with their written content,
    - Embedded or linked educational videos\n"
    - At least 10 multiple-choice quiz questions per session,
    - A hands-on project at the end of each section,
    - Proper formatting for publication or API delivery (json).
  agent: Course_compiler
  context:
    - Course_planner_task
    - content_writer_task
    - Quiz_builder_task
    - project_builder_task